# Generated by Django 2.2.5 on 2019-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbf_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('player_class', models.CharField(max_length=30)),
            ],
        ),
    ]
